server:
  port: 9093

grpc:
  server:
    port: 7073
  address:
    name: localhost
    service-port:
      user: 7072

spring:
  application:
    name: vehicle-owner-service
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle-owner-service
    username: postgres
    password: Root@123
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

logging:
  level:
    liquibase: DEBUG
